package com.akyljer.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity for Crop Task
 * 
 * Stores AI-generated or manual tasks for crop management.
 * Generated by Crop Advisor based on field conditions and weather.
 */
@Entity(
    tableName = "crop_tasks",
    foreignKeys = [
        ForeignKey(
            entity = FieldEntity::class,
            parentColumns = ["id"],
            childColumns = ["field_id"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["field_id"]), Index(value = ["due_date"])]
)
data class CropTaskEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: String,
    
    @ColumnInfo(name = "field_id")
    val fieldId: String? = null,
    
    @ColumnInfo(name = "title")
    val title: String,
    
    @ColumnInfo(name = "description")
    val description: String,
    
    @ColumnInfo(name = "task_type")
    val taskType: String, // IRRIGATION, FERTILIZATION, PEST_CONTROL, HARVESTING, OTHER
    
    @ColumnInfo(name = "priority")
    val priority: String, // LOW, MEDIUM, HIGH, CRITICAL
    
    @ColumnInfo(name = "due_date")
    val dueDate: Long,
    
    @ColumnInfo(name = "is_completed")
    val isCompleted: Boolean = false,
    
    @ColumnInfo(name = "completed_at")
    val completedAt: Long? = null,
    
    @ColumnInfo(name = "source")
    val source: String = "AI", // AI, MANUAL, WEATHER_ALERT
    
    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
)
