package com.akyljer.data.local.dao

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.akyljer.data.local.entity.CropTaskEntity
import kotlinx.coroutines.flow.Flow

/**
 * DAO for Crop Task operations
 * 
 * Manages tasks generated by Crop Advisor or created manually.
 * Supports filtering by completion status, priority, and field.
 */
@Dao
interface CropTaskDao {
    
    /**
     * Get all tasks as Flow (reactive)
     */
    @Query("SELECT * FROM crop_tasks ORDER BY due_date ASC, priority DESC")
    fun getAllTasks(): Flow<List<CropTaskEntity>>
    
    /**
     * Get pending (incomplete) tasks
     */
    @Query("SELECT * FROM crop_tasks WHERE is_completed = 0 ORDER BY due_date ASC, priority DESC")
    fun getPendingTasks(): Flow<List<CropTaskEntity>>
    
    /**
     * Get completed tasks
     */
    @Query("SELECT * FROM crop_tasks WHERE is_completed = 1 ORDER BY completed_at DESC")
    fun getCompletedTasks(): Flow<List<CropTaskEntity>>
    
    /**
     * Get tasks for a specific field
     */
    @Query("SELECT * FROM crop_tasks WHERE field_id = :fieldId ORDER BY due_date ASC")
    fun getTasksByField(fieldId: String): Flow<List<CropTaskEntity>>
    
    /**
     * Get pending tasks for a specific field
     */
    @Query("SELECT * FROM crop_tasks WHERE field_id = :fieldId AND is_completed = 0 ORDER BY due_date ASC")
    fun getPendingTasksByField(fieldId: String): Flow<List<CropTaskEntity>>
    
    /**
     * Get tasks by priority
     */
    @Query("SELECT * FROM crop_tasks WHERE priority = :priority AND is_completed = 0 ORDER BY due_date ASC")
    fun getTasksByPriority(priority: String): Flow<List<CropTaskEntity>>
    
    /**
     * Get high priority pending tasks
     */
    @Query("SELECT * FROM crop_tasks WHERE priority IN ('HIGH', 'CRITICAL') AND is_completed = 0 ORDER BY due_date ASC")
    fun getHighPriorityTasks(): Flow<List<CropTaskEntity>>
    
    /**
     * Get overdue tasks
     */
    @Query("SELECT * FROM crop_tasks WHERE is_completed = 0 AND due_date < :currentTime ORDER BY due_date ASC")
    fun getOverdueTasks(currentTime: Long = System.currentTimeMillis()): Flow<List<CropTaskEntity>>
    
    /**
     * Get task by ID as Flow
     */
    @Query("SELECT * FROM crop_tasks WHERE id = :taskId")
    fun getTaskById(taskId: String): Flow<CropTaskEntity?>
    
    /**
     * Get task by ID (one-time)
     */
    @Query("SELECT * FROM crop_tasks WHERE id = :taskId")
    suspend fun getTaskByIdOnce(taskId: String): CropTaskEntity?
    
    /**
     * Insert new task
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTask(task: CropTaskEntity)
    
    /**
     * Insert multiple tasks
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertTasks(tasks: List<CropTaskEntity>)
    
    /**
     * Update task
     */
    @Update
    suspend fun updateTask(task: CropTaskEntity)
    
    /**
     * Mark task as completed
     */
    @Query("UPDATE crop_tasks SET is_completed = 1, completed_at = :completedAt WHERE id = :taskId")
    suspend fun markTaskCompleted(taskId: String, completedAt: Long = System.currentTimeMillis())
    
    /**
     * Mark task as incomplete
     */
    @Query("UPDATE crop_tasks SET is_completed = 0, completed_at = NULL WHERE id = :taskId")
    suspend fun markTaskIncomplete(taskId: String)
    
    /**
     * Delete task
     */
    @Delete
    suspend fun deleteTask(task: CropTaskEntity)
    
    /**
     * Delete task by ID
     */
    @Query("DELETE FROM crop_tasks WHERE id = :taskId")
    suspend fun deleteTaskById(taskId: String)
    
    /**
     * Delete all completed tasks
     */
    @Query("DELETE FROM crop_tasks WHERE is_completed = 1")
    suspend fun deleteCompletedTasks()
    
    /**
     * Get pending task count
     */
    @Query("SELECT COUNT(*) FROM crop_tasks WHERE is_completed = 0")
    suspend fun getPendingTaskCount(): Int
    
    /**
     * Get overdue task count
     */
    @Query("SELECT COUNT(*) FROM crop_tasks WHERE is_completed = 0 AND due_date < :currentTime")
    suspend fun getOverdueTaskCount(currentTime: Long = System.currentTimeMillis()): Int
    
    /**
     * Delete all tasks (for testing)
     */
    @Query("DELETE FROM crop_tasks")
    suspend fun deleteAllTasks()
}
